name: build
run-name: "build ${{ inputs.packages }}"

permissions: {}

on:
  workflow_dispatch:
    inputs:
      packages:
        description: "Packages"
        required: false
        type: string
      x86_64-linux:
        description: "Build on x86_64-linux"
        required: true
        type: boolean
        default: true
      aarch64-linux:
        description: "Build on aarch64-linux"
        required: true
        type: boolean
        default: true
      x86_64-darwin:
        description: "Build on x86_64-darwin"
        required: true
        type: choice
        default: yes_sandbox_true
        options:
          - 'no'
          - yes_sandbox_false
          - yes_sandbox_relaxed
          - yes_sandbox_true
      aarch64-darwin:
        description: "Build on aarch64-darwin"
        required: true
        type: choice
        default: yes_sandbox_true
        options:
          - 'no'
          - yes_sandbox_false
          - yes_sandbox_relaxed
          - yes_sandbox_true
      upterm:
        description: "Start upterm session after nix build"
        required: true
        type: boolean
        default: false

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        system:
          - x86_64-linux
          - aarch64-linux
          - x86_64-darwin
          - aarch64-darwin
        exclude:
          - system: ${{ !inputs.x86_64-linux && 'x86_64-linux' || '' }}
          - system: ${{ !inputs.aarch64-linux && 'aarch64-linux' || '' }}
          - system: ${{ inputs.x86_64-darwin == 'no' && 'x86_64-darwin' || '' }}
          - system: ${{ inputs.aarch64-darwin == 'no' && 'aarch64-darwin' || '' }}
    runs-on: >-
      ${{ (matrix.system == 'x86_64-linux' && 'ubuntu-latest')
      || (matrix.system == 'aarch64-linux' && 'ubuntu-24.04-arm')
      || (matrix.system == 'x86_64-darwin' && 'macos-13')
      || (matrix.system == 'aarch64-darwin' && 'macos-latest') }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: prepare /nix
        run: sudo mkdir /mnt/nix && sudo mount -m -o bind /mnt/nix /nix
        if: ${{ matrix.system == 'x86_64-linux' || matrix.system == 'aarch64-linux' }}

      - name: install nix
        uses: cachix/install-nix-action@17fe5fb4a23ad6cbbe47d6b3f359611ad276644c # v31.4.0
        with:
          extra_nix_config: |
            sandbox = ${{
              (matrix.system == 'x86_64-darwin' && inputs.x86_64-darwin == 'yes_sandbox_false'
                || matrix.system == 'aarch64-darwin' && inputs.aarch64-darwin == 'yes_sandbox_false') && 'false'
              || (matrix.system == 'x86_64-darwin' && inputs.x86_64-darwin == 'yes_sandbox_relaxed'
                || matrix.system == 'aarch64-darwin' && inputs.aarch64-darwin == 'yes_sandbox_relaxed') && 'relaxed'
              || 'true' }}

      - name: nix build
        run: nix build --keep-going -L ${{ inputs.packages }}
        if: ${{ inputs.packages != '' }}

      - name: start upterm session
        if: ${{ inputs.upterm }}
        uses: owenthereal/action-upterm@57dc63cab27f7891d9ce116ee4bce34a2fe041a3 # v1.2.0
        with:
          limit-access-to-actor: true
